<a href="https://colab.research.google.com/github/MegaCharizardZ/Nanomagnetics/blob/main/J_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%reset -s -f

In [2]:
import numpy as np  

In [3]:
u1=np.matrix('1,-1,-1,-1').transpose()
u1

matrix([[ 1],
        [-1],
        [-1],
        [-1]])

In [4]:
u2=np.matrix('1,-1,1,-1').transpose()
u3=np.matrix('1,1,-1,-1').transpose()
u4=np.matrix('1,1,1,1').transpose()

In [5]:
U=np.concatenate((u1,u2,u3,u4), axis=1)
U

matrix([[ 1,  1,  1,  1],
        [-1, -1,  1,  1],
        [-1,  1, -1,  1],
        [-1, -1, -1,  1]])

In [6]:
S=np.matmul(U.transpose(),U)
S
np.linalg.det(S)

63.99999999999998

In [7]:
J=np.linalg.inv(S)*(np.matmul(u1,u1.transpose())+np.matmul(u2,u2.transpose())+np.matmul(u3,u3.transpose())+np.matmul(u4,u4.transpose()))
J

matrix([[ 3.00000000e+00, -1.00000000e+00, -1.00000000e+00,
         -2.00000000e+00],
        [-1.50000000e+00,  1.50000000e+00,  5.00000000e-01,
          1.50000000e+00],
        [-1.50000000e+00,  5.00000000e-01,  1.50000000e+00,
          1.50000000e+00],
        [ 1.00000000e+00,  1.11022302e-16,  2.22044605e-16,
          4.44089210e-16]])

In [8]:
J=np.linalg.inv(S)[0,0]*np.matmul(u1,u1.transpose())+np.linalg.inv(S)[0,1]*np.matmul(u1,u2.transpose())+np.linalg.inv(S)[1,0]*np.matmul(u2,u1.transpose())+np.linalg.inv(S)[1,1]*np.matmul(u2,u2.transpose())+np.linalg.inv(S)[2,1]*np.matmul(u3,u2.transpose())+np.linalg.inv(S)[1,2]*np.matmul(u2,u3.transpose())+np.linalg.inv(S)[2,2]*np.matmul(u3,u3.transpose())+np.linalg.inv(S)[2,3]*np.matmul(u3,u4.transpose())+np.linalg.inv(S)[3,2]*np.matmul(u4,u3.transpose())+np.linalg.inv(S)[3,3]*np.matmul(u4,u4.transpose())





J



matrix([[ 1.50000000e+00,  0.00000000e+00, -5.00000000e-01,
         -1.00000000e+00],
        [ 1.11022302e-16,  5.00000000e-01,  1.00000000e+00,
          5.00000000e-01],
        [-5.00000000e-01,  1.00000000e+00,  3.50000000e+00,
          2.00000000e+00],
        [-1.00000000e+00,  5.00000000e-01,  2.00000000e+00,
          2.50000000e+00]])

In [9]:
import math
for i in range(4):
  for j in range(4):
    J[i,j]=2*J[i,j]
    J[i,j]=math.floor(J[i,j])
  J[i,i]=0
J

matrix([[ 0.,  0., -1., -2.],
        [ 0.,  0.,  1.,  1.],
        [-1.,  1.,  0.,  3.],
        [-2.,  1.,  3.,  0.]])

In [10]:
J*=2
for i in range(4):
  for j in range(4):
    J[i,j]=int(J[i,j])
for i in range(4):
  J[i,i]=0
J

matrix([[ 0.,  0., -2., -4.],
        [ 0.,  0.,  2.,  2.],
        [-2.,  2.,  0.,  6.],
        [-4.,  2.,  6.,  0.]])

In [11]:
np.matmul(u1,u1.transpose())

matrix([[ 1, -1, -1, -1],
        [-1,  1,  1,  1],
        [-1,  1,  1,  1],
        [-1,  1,  1,  1]])

In [12]:
J=np.array([[0,0,-1,-2],[0,0,2,1],[-1,2,0,4],[-2,1,4,0]])
J

array([[ 0,  0, -1, -2],
       [ 0,  0,  2,  1],
       [-1,  2,  0,  4],
       [-2,  1,  4,  0]])