In [1]:
%reset -s -f

In [2]:
import numpy as np

In [3]:
u1=np.matrix('-1,1,1,1,1,-1,-1,-1').transpose()
u1

matrix([[-1],
        [ 1],
        [ 1],
        [ 1],
        [ 1],
        [-1],
        [-1],
        [-1]])

In [4]:
u2=np.matrix('1,-1,-1,1,1,-1,1,-1').transpose()
u3=np.matrix('1,-1,1,-1,1,1,-1,-1').transpose()
u4=np.matrix('1,1,1,1,1,1,1,1').transpose()

In [5]:
U=np.concatenate((u1,u2,u3,u4), axis=1)
U

matrix([[-1,  1,  1,  1],
        [ 1, -1, -1,  1],
        [ 1, -1,  1,  1],
        [ 1,  1, -1,  1],
        [ 1,  1,  1,  1],
        [-1, -1,  1,  1],
        [-1,  1, -1,  1],
        [-1, -1, -1,  1]])

In [6]:
S=np.matmul(U.transpose(),U)
S

matrix([[8, 0, 0, 0],
        [0, 8, 0, 0],
        [0, 0, 8, 0],
        [0, 0, 0, 8]])

In [7]:
J=1/8.0*(np.matmul(u1,u1.transpose())+np.matmul(u2,u2.transpose())+np.matmul(u3,u3.transpose())+np.matmul(u4,u4.transpose()))

In [8]:
J

matrix([[ 0.5 , -0.25,  0.  ,  0.  ,  0.25,  0.25,  0.25,  0.  ],
        [-0.25,  0.5 ,  0.25,  0.25,  0.  ,  0.  ,  0.  ,  0.25],
        [ 0.  ,  0.25,  0.5 ,  0.  ,  0.25,  0.25, -0.25,  0.  ],
        [ 0.  ,  0.25,  0.  ,  0.5 ,  0.25, -0.25,  0.25,  0.  ],
        [ 0.25,  0.  ,  0.25,  0.25,  0.5 ,  0.  ,  0.  , -0.25],
        [ 0.25,  0.  ,  0.25, -0.25,  0.  ,  0.5 ,  0.  ,  0.25],
        [ 0.25,  0.  , -0.25,  0.25,  0.  ,  0.  ,  0.5 ,  0.25],
        [ 0.  ,  0.25,  0.  ,  0.  , -0.25,  0.25,  0.25,  0.5 ]])

In [9]:
for i in range(8):
    J[i,i]=0

In [10]:
J

matrix([[ 0.  , -0.25,  0.  ,  0.  ,  0.25,  0.25,  0.25,  0.  ],
        [-0.25,  0.  ,  0.25,  0.25,  0.  ,  0.  ,  0.  ,  0.25],
        [ 0.  ,  0.25,  0.  ,  0.  ,  0.25,  0.25, -0.25,  0.  ],
        [ 0.  ,  0.25,  0.  ,  0.  ,  0.25, -0.25,  0.25,  0.  ],
        [ 0.25,  0.  ,  0.25,  0.25,  0.  ,  0.  ,  0.  , -0.25],
        [ 0.25,  0.  ,  0.25, -0.25,  0.  ,  0.  ,  0.  ,  0.25],
        [ 0.25,  0.  , -0.25,  0.25,  0.  ,  0.  ,  0.  ,  0.25],
        [ 0.  ,  0.25,  0.  ,  0.  , -0.25,  0.25,  0.25,  0.  ]])

In [11]:
J*4

matrix([[ 0., -1.,  0.,  0.,  1.,  1.,  1.,  0.],
        [-1.,  0.,  1.,  1.,  0.,  0.,  0.,  1.],
        [ 0.,  1.,  0.,  0.,  1.,  1., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  1., -1.,  1.,  0.],
        [ 1.,  0.,  1.,  1.,  0.,  0.,  0., -1.],
        [ 1.,  0.,  1., -1.,  0.,  0.,  0.,  1.],
        [ 1.,  0., -1.,  1.,  0.,  0.,  0.,  1.],
        [ 0.,  1.,  0.,  0., -1.,  1.,  1.,  0.]])